### ISSUE TITLE
working with Alonzo upgrade?

### ISSUE THREAD

**Issue by cardanative** [shareslake/cardanocli-js#12]
Hi guys, 

Is the library still working with node 1.29.0 ?
I saw a couple of addition in cardano-cli and was wondering if the lib is still working  (even if it does not include the upgrade)

Thanks

**Comment by Cyb3rDudu** [comment]
With little hacks it can work with node 1.29.0

https://github.com/Berry-Pool/cardanocli-js/issues/13#issuecomment-914453974

and

https://github.com/Berry-Pool/cardanocli-js/pull/10/files

**Comment by cardanative** [comment]
Thanks and new version has been added by the owner.
Thanks

**Comment by miguelaeh** [comment]
Hi @cardanative ,
I am closing the issue since looks to be resolved, feel free to repone it.
