### ISSUE TITLE
getBalance (query utxo) returning undefined: NaN on V1.29.0 (Alonzo)

### ISSUE THREAD

**Issue by abdellahaski** [shareslake/cardanocli-js#13]
Hello,
Apparently, this library needs an update for the Alonzo update, getting the balance input an `undefined: NaN` on the output:
![image](https://user-images.githubusercontent.com/10819089/131931675-ea93f3ab-8f23-4096-a2bc-287d9eec290b.png)

here is the output of cardano-cli shelley query utxo:
![image](https://user-images.githubusercontent.com/10819089/131931770-c84df90f-180e-46ee-a5b9-ddbcd5aad3f6.png)

I think that it's "TxOutDatumHashNone" that's resulting into the `undefined: NaN`

This does break also building transaction and so on

**Comment by Cyb3rDudu** [comment]
I could workaround it by skipping "TxOutDatumHashNone" when the values from the UTXO's lists are parsed.
In `cardanocli-js/index.js` i wrapped the assignment of the assets values like bellow.

Should be in l225 or near there (I made some more hacks for testing purposes)
````
    valueList.forEach((v) => {
      if (v != " TxOutDatumHashNone") {
        let [quantity, asset] = v.trim().split(" ");
        quantity = parseInt(quantity);
        value[asset] = quantity;
      };
    });
````
The leading whitespace is important!

Not sure, if this is the right solution but at least I can proceed minting with my v1.29 node

**Comment by gabacode** [comment]
The way I did it was to simply remove the undefined property from the object, like this:

```
let current = wallet.balance().amount
delete current.undefined
console.log(current)
```

**Comment by javiergradiche** [comment]
@alessandrokonrad fixed in PR https://github.com/Berry-Pool/cardanocli-js/pull/23, take a look and merge it, please.

**Comment by miguelaeh** [comment]
The PR was merged, I guess we can close the issue right?
