### ISSUE TITLE
NPM package version at 4.0.0

### ISSUE THREAD

**Issue by pyropy** [shareslake/cardanocli-js#18]
Hi !

It seems like the npm package is still at v4.0.0. while package version in repository is v4.0.1

![Screenshot 2021-09-15 at 11 40 49](https://user-images.githubusercontent.com/30221068/133410465-7e2fa386-c3a7-4a66-a5be-b1f6f4579ea0.png)

**Comment by Saifadin** [comment]
@alessandrokonrad is it possible to release the new version that fixes that pesky space?^^

**Comment by pyropy** [comment]
For anyone looking for the temporary workaround u can install package directly from GitHub:

Using npm:

```bash
npm install Berry-Pool/cardanocli-js
```

Or by using yarn:

```bash
yarn add Berry-Pool/cardanocli-js
```

**Comment by pyropy** [comment]
Seems to be updated, closing the issue. @alessandrokonrad Thank you for creating and maintaining the package!
