### ISSUE TITLE
tryParseJson does not return parsed json

### ISSUE THREAD

**Issue by intob** [shareslake/cardanocli-js#2]
https://github.com/Berry-Pool/cardanocli-js/blob/cafde0c3d348d2779cad8ed0239d186d0d194545/helper.js#L97

Hi Alessandro,

The exported method `tryParseJson()` in `helper.js#97` does not return parsed json, but it returns `true` if the json was parsed and result is of type object. If this method should only validate the json string, I suggest renaming the method. Otherwise maybe you meant to `return result`.

Have a great day :)

**Comment by alessandrokonrad** [comment]
Hey,
thanks for the feedback. I'll change that in the next release!
