### ISSUE TITLE
Connecting cardano-node with httpProvider?

### ISSUE THREAD

**Issue by lukaske** [shareslake/cardanocli-js#20]
Hi,

has anyone had success with connecting to a remote node using the httpProvider settings? 

I've tried node version 1.30.1 and 1.29.0 - both fail to connect via httpProvider. Tried looking into the official node docker itself, it seems like the cardano-node is returning empty server responses. Has this feature been deprecated or is there something else I'm doing wrong?

Thanks for any suggestions!

**Comment by miguelaeh** [comment]
Could you please share the code you are using for such connection and the errors you are getting?

**Comment by dcolley** [comment]
I have the same question.

I'm running `cardano-relay` and `cardano-node` on docker.
Do we need a `cardano-submit-api` server from here? https://github.com/input-output-hk/cardano-node/blob/master/docker-compose.yml

Which server should we connect to, and what port should we expose on the server?

**Comment by lukaske** [comment]
The correct way to connect is via [Berry-Pool/cardanocli-rest](https://github.com/Berry-Pool/cardanocli-rest). 

I put these servers in a docker-compose env. But beware of some issues with the cardano-node, sometimes it would lose unix socket connection to the synced blockchain file (such as when restarting docker-compose) and would take over 24h to resync.

**Comment by dcolley** [comment]
Thanks, that worked!

For reference, I made a docker for cardano-cli-rest here
https://github.com/metaspan/cardanocli-rest-docker

**Comment by miguelaeh** [comment]
Glad you solve it! Feel free to re-open if needed
