### ISSUE TITLE
example  simple transaction is not working

### ISSUE THREAD

**Issue by fisch192** [shareslake/cardanocli-js#21]
I´m getting always the error : 
```
Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (ValueNotConservedUTxO (Value 8077275 (fromList [(PolicyID {policyID = ScriptHash
```

Any idea

**Comment by miguelaeh** [comment]
Hi @fisch192 ,
That error means the Lovelace amount into the inputs of your TX do not match the amount on the outputs.
It does not look to be an issue with the library so I will close the case, feel free to reopen it if you find an issue with the library itself.
