### ISSUE TITLE
Error: Command failed: cardano-cli transaction build-raw

### ISSUE THREAD

**Issue by mhdmazaz** [shareslake/cardanocli-js#22]
Hey everyone,

An error is caused when trying to submit a transaction using the code in the examples directory. 

Version: cardanocli-js@4.0.1

The error message:
```
option --tx-out: 
unexpected "N"
expecting white space or multi-asset value expression

```

After debugging I found out the the balance and keyDeposit aree both undefined at the following code:

```
const registerWallet = (wallet) => {
  let account = wallet.name;
  let keyDeposit = cardanocliJs.queryProtocolParameters().keyDeposit;
  let stakeCert = cardanocliJs.stakeAddressRegistrationCertificate(account);
  let paymentAddress = cardanocliJs.wallet(account).paymentAddr;
  let balance = cardanocliJs.wallet(account).balance().value.lovelace;
```

and if you look at the tx there is a value which should be appended to the payment address:

```
let tx = {
    txIn: cardanocliJs.queryUtxo(paymentAddress),
    txOut: [
      { address: paymentAddress, value: { lovelace: balance - keyDeposit } },
    ],
    certs: [{ cert: stakeCert }],
    witnessCount: 2,
  };
```

in JS:
` undefined - undefined = NaN
`

at the end the --tx-out is something like this:
`--tx-out "addr_test1qz0vzjnra5rq702lv0x4cr8y9f56gcy07yufwfq8gekuaw24k7uzykt655k2gx5438q54xm5yunwsvaevrk9k80uasuqcxwlmv+NaN"
`

see at NaN appended at the end.

After I fix this and put 0 as a value instead. I get another error :

`Missing: (--tx-in TX-IN)
`

Did I miss something? is this expected ?

I used the following code:

const createWallet = (account) => {
  const payment = cardanocliJs.addressKeyGen(account);
  const stake = cardanocliJs.stakeAddressKeyGen(account);
  cardanocliJs.stakeAddressBuild(account);
  cardanocliJs.addressBuild(account, {
    paymentVkey: payment.vkey,
    stakeVkey: stake.vkey,
  });
  return cardanocliJs.wallet(account);
};

const registerWallet = (wallet) => {
  let account = wallet.name;
  let keyDeposit = cardanocliJs.queryProtocolParameters().keyDeposit;
  let stakeCert = cardanocliJs.stakeAddressRegistrationCertificate(account);
  let paymentAddress = cardanocliJs.wallet(account).paymentAddr;
  let balance = cardanocliJs.wallet(account).balance().value.lovelace;
  console.log("balance");
  console.log(balance);
  console.log("keyDeposit");
  console.log(keyDeposit);

  let tx = {
    txIn: cardanocliJs.queryUtxo(paymentAddress),
    txOut: [
      { address: paymentAddress, value: { lovelace: balance - keyDeposit } },
    ],
    certs: [{ cert: stakeCert }],
    witnessCount: 2,
  };
  let txBodyRaw = cardanocliJs.transactionBuildRaw(tx);
  let fee = cardanocliJs.transactionCalculateMinFee({
    ...tx,
    txBody: txBodyRaw,
  });
  tx.txOut[0].value.lovelace -= fee;
  let txBody = cardanocliJs.transactionBuildRaw({ ...tx, fee });
  let txSigned = cardanocliJs.transactionSign({
    txBody,
    signingKeys: [
      cardanocliJs.wallet(account).payment.skey,
      cardanocliJs.wallet(account).stake.skey,
    ],
  });

  return txSigned;
};`
`

**_Forgot to add:
cardano-node 1.30.1 - darwin-x86_64 - ghc-8.10
cardano-cli 1.30.1 - darwin-x86_64 - ghc-8.10_**

**Comment by draschke** [comment]
Have the same issue.

vscode ➜ /cardano/cardanocli-js (main ✗) $ npm list
cardanocli-js@ /cardano/cardanocli-js
└── cardanocli-js@4.0.1

vscode ➜ /cardano/cardanocli-js (main ✗) $ npm list -g
/usr/local/share/nvm/versions/node/v16.13.1/lib
├── corepack@0.10.0
└── npm@8.1.2

$ cardano-cli --version
cardano-cli 1.32.1 - linux-x86_64 - ghc-8.10
git rev 4f65fb9a27aa7e3a1873ab4211e412af780a3648

**Comment by mhdmazaz** [comment]
If I remember correctly, you need to add fund in order to make it work.

**Comment by draschke** [comment]
@mhdmazaz 
I'm a newbie. Could it be that the parameter **keyDeposit** has changed to **stakeAddressDeposit**?

  // let keyDeposit = cardanocliJs.queryProtocolParameters().**keyDeposit**;
  let keyDeposit = cardanocliJs.queryProtocolParameters().**stakeAddressDeposit**;

**Comment by mhdmazaz** [comment]
I'm really not sure. I ended up (with my team member) writing a new JS CLI from scratch. We are publishing it soon.

Anyway, did you add fund already?

**Comment by draschke** [comment]
Anyway, did you add fund already?
> No, I didn't.  
Do I have to add tADA to this created addr_test1qrwx5zxglhvnsv....?

**Comment by mhdmazaz** [comment]
Yes, you should do that.

**Comment by miguelaeh** [comment]
Hi guys,
I have checked and looks like you are right, the `keyDeposit` was changed to `stakeAddressDeposit` when querying the protocol parameters.
Also, when performing this action note that the balance must be greater than the `stakeAddressDeposit`.

**Comment by miguelaeh** [comment]
You can check the above PR, it should fix the issue
