### ISSUE TITLE
Address is added 2 times

### ISSUE THREAD

**Issue by edwint88** [shareslake/cardanocli-js#35]
Now that the `multiAssetToString` function is changed and actually needs the `options` not the `value` anymore, then this function should take an `options` as param and remove the address from tx-out

https://github.com/Berry-Pool/cardanocli-js/blob/1bad5330f6c3c1af74503caa443c1270fc7c695a/index.js#L1219

**Comment by miguelaeh** [comment]
Hi @edwint88 ,
Would you like to create a PR with those changes?
