### ISSUE TITLE
syntax in txOutToString of helper.js

### ISSUE THREAD

**Issue by osephson** [shareslake/cardanocli-js#47]
Hi, I'm new to Cardano and trying to mint NFTs with it.
While building a transaction, I've got an error.
```
option --tx-out: 
unexpected "u"
expecting white space or multi-asset value expression
```
After debugging, I found out the syntax of `txOutToString` is different from [syntax breakdown](https://developers.cardano.org/docs/native-tokens/minting/#syntax-breakdown).

Here is the code of `txOutToString`.
```
exports.txOutToString = (txOutList) => {
  let result = "";
  txOutList.forEach((txOut) => {
    result += `--tx-out "${txOut.address}+${txOut.value.lovelace}`;
    Object.keys(txOut.value).forEach((asset) => {
      if (asset == "lovelace") return;
      result += `+${txOut.value[asset]} ${asset}`;
    });
    result += `" `;
    txOut.datumHash && (result += `--tx-out-datum-hash ${txOut.datumHash}`);
  });
  return result;
};
```

As far as I know, the quote mark(`"`) after `--tx-out ` should be placed before `txOut.value[asset]`. Am I wrong?

**Comment by miguelaeh** [comment]
It looks like you are right. Regarding the link you shared, the quotes should be before the multi assets part. Nevertheless, I am not fully sure that's the issue since I can't identify with the error log posted which `u` does it refers to. Did you test the suggested solution? Would you like to open a PR fixing it?

**Comment by osephson** [comment]
Can you add me as a collaborator, please?

**Comment by miguelaeh** [comment]
Hi @osephson ,
It shouldn't be needed, if you fork the repo then you should be able to create a PR
