### ISSUE TITLE
communication with remote/docker cardano-node

### ISSUE THREAD

**Issue by hussamBim** [shareslake/cardanocli-js#55]
Hi, I am using your package for minting, transfer. But i want to make connect of local cardano-cli with my remote cardano-node which is hosted on aws server or in some docker container.

**Comment by miguelaeh** [comment]
Hi @hussamBim ,

This library by default uses the `CARDANO_NODE_SOCKET_PATH` env var to connect with the local Cardano node, like the `cardano-cli` tool. If you want to connect to a remote node you need to configure the `httpProvider`. Check [this](https://github.com/shareslake/cardanocli-js/blob/1bad5330f6c3c1af74503caa443c1270fc7c695a/API.md#new-cardanoclijsoptions).

**Comment by hussamBim** [comment]
Hi @miguelaeh 

I have done that but getting errors of connection refused from server side.

I have my testnet node running on aws ec2 instance working fine on server. How i can connect that can you please guide about that?

**Comment by miguelaeh** [comment]
Hi @hussamBim ,
I am sorry for the late response. I think it is not enough just with the Cardano node, you would need the Cardano api. Nevertheless,
You can check in the code there are calls like:
```
      let response = fetch(
        `${this.httpProvider}/queryStakeAddressInfo/${address}`
      );
```

Now, I think it uses a deprecated API, so I would use it along with the node and use other libraries when submitting transactions remotely, like CSL and cardano-submit-api
