### ISSUE TITLE
TimeLocked Policy ID not minting

### ISSUE THREAD

**Issue by hussamBim** [shareslake/cardanocli-js#61]
My Policy Script is this that it will be locked after 1 year.
const mintScript = {
    type: "all",
    scripts: [
      {
        type: "before",
        slot: 71547800 + 31104000,
      },
      {
        type: "sig",
        keyHash: "keyHash",
      }
    ],
  };

It gives this error when i try to mint:

Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (ScriptWitnessNotValidatingUTXOW (fromList [ScriptHash "1c3b364275705dec7394647f3b046fc8bf36fe43fa8655a116ad71f8"]))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (OutsideValidityIntervalUTxO (ValidityInterval {invalidBefore = SJust (SlotNo 71554239), invalidHereafter = SJust (SlotNo 71558911)}) (SlotNo 71548912))))])

**Comment by miguelaeh** [comment]
@hussamBim please give a try with the new version and feel free to reopen the issue if it persists
