### ISSUE TITLE
basic stuff does not work

### ISSUE THREAD

**Issue by reitcircles** [shareslake/cardanocli-js#63]
cardanocliJs.addressBuild(account); does not work.

Simple example: https://developers.cardano.org/docs/get-started/cardanocli-js/ on this page does not work ...what to talk of others... Frustrating ...

**Comment by reitcircles** [comment]
Uncaught TypeError: Cannot read property 'paymentVkey' of undefined
    at CardanocliJs.addressBuild (node_modules/cardanocli-js/index.js:345:33)

**Comment by reitcircles** [comment]
documentation is not updated. Found the solution by browsing code.

this is the basic example now:
` const createWallet = (account) => {
            let a1 = cardanocliJs.addressKeyGen(account);
            let s1 = cardanocliJs.stakeAddressKeyGen(account);
            cardanocliJs.stakeAddressBuild(account);
            cardanocliJs.addressBuild(account,{ "paymentVkey": a1.vkey });
            return cardanocliJs.wallet(account);
        };`

**Comment by miguelaeh** [comment]
Glad you found the solution, closing the issue. Fee free to reopen if you find issues with the new version
